name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - run: |
           sudo apt-get update
           sudo apt install g++-10 gcc-10 cmake ninja-build
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir build
    - name: configure
      working-directory: ./build
      run: cmake -G Ninja ..
    - name: compile
      run: ninja -C build
    - name: test
      working-directory: ./build
      run: ctest
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: setup
      run: md build 
    - name: configure
      working-directory: ./build
      run: cmake -DCVD_ENABLE_PROGS=OFF -DCVD_ENABLE_TESTS=OFF -DCVD_ENABLE_EXAMPLES=OFF ..
    - name: compile
      working-directory: ./build
      run: msbuild CVD.sln



